# Generated by Django 6.0.4 on 2026-05-03 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('locations', models.ManyToManyField(related_name='visitors', to='collection.location')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('detective', 'Detective'), ('novel', 'Novel'), ('other', 'Other')], default='other', max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='collection.location')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='collection.visitor')),
            ],
        ),
    ]
